server:
  port: 8080

spring:
  profiles:
    active: @spring.profiles.active@

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${govion.host}/${govion.database}?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ${govion.username}
    password: ${govion.password}
logging:
  config: classpath:log4j2.xml

mybatis-plus:
  #  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    # 开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  type-aliases-package: com.govion.goinfo.Bean
